AWSTemplateFormatVersion: '2010-09-09'
Description: Private ECR repository for GitOps build images

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: gitops-ecr
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
    Export:
      Name: gitops-ecr-uri
  RepositoryArn:
    Value: !GetAtt Repository.Arn
    Export:
      Name: gitops-ecr-arn
