# deploy without key:
# aws cloudformation deploy --stack-name simple-ec2-python --template-file ./cloudformation/ec2-simple-python/template.cform.yaml

# deploy with key:
# KEYPAIR_NAME="default"
# aws ec2 create-key-pair --key-name $KEYPAIR_NAME --query "KeyMaterial" --output text > $HOME/$KEYPAIR_NAME.pem
# aws cloudformation deploy --stack-name simple-ec2-python --template-file ./cloudformation/ec2-simple-python/template.cform.yaml --parameter-overrides KeyName=$KEYPAIR_NAME

# aws cloudformation deploy --stack-name simple-ec2-python --template-file cloudformation/ec2-simple-python/template.cform.yaml --parameter-overrides KeyName=$KEYPAIR_NAME
# PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name simple-ec2-python --query "Stacks[0].Outputs[?OutputKey=='InstancePublicIP'].OutputValue" --output text)

# echo "http://$PUBLIC_IP"
# time curl "http://${PUBLIC_IP}/tuna-1.png" -o /dev/null
# time ab -k -r -n 1024 -c 16 "http://${PUBLIC_IP}/tuna-1.png"

Description: EC2 instance running k3s

Parameters:
  TenantId:
    Type: String
    Default: Main
  
  EnvId:
    Type: String
    Default: Main

  InstanceType:
    Type: String
    Default: t4g.small

  AmiSsmParameter:
    Type: String
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64
    Description: SSM parameter name resolving to the desired AMI ID

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
    Default: ""

  GitHubUser:
    Description: GitHub username owning the repo
    Type: String
    Default: "DAWS25"

  GitHubRepo:
    Description: GitHub repository name
    Type: String
    Default: "daws"

  DetailedMonitoring:
    Type: String
    Default: "false"
    AllowedValues: ["true","false"]
    Description: Enable CloudWatch detailed monitoring for the instance [+- 2.10/instance/month]

  VolumeSize:
    Type: Number
    Default: 64
  
  VolumeType:
    Type: String
    Default: gp3

  K3sPort:
    Type: Number
    Default: 6443
  

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, ""]]

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref K3sPort
          ToPort: !Ref K3sPort
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  K3sInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref "AWS::NoValue"]
      ImageId: !Sub "{{resolve:ssm:${AmiSsmParameter}}}"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Monitoring: !Ref DetailedMonitoring
      Tags:
        - Key: Name
          Value: K3sInstance
        - Key: ARTIFACTS_BUCKET
          Value: !ImportValue
            Fn::Sub: ${TenantId}-${EnvId}-GitopsArtifactsBucketName
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: !Ref VolumeSize
          VolumeType: !Ref VolumeType
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          USER_DATA_PATH="user-data/k3s/user-data.sh"
          ##
          echo "User data script started for [$USER_DATA_PATH]" | tee -a /home/ec2-user/user-data.log
          yum update -y
          yum install -y unzip python3 wget
          cd /home/ec2-user
          echo "Downloading repository from GitHub: ${GitHubUser}/${GitHubRepo}" | tee -a /home/ec2-user/user-data.log
          wget https://github.com/${GitHubUser}/${GitHubRepo}/archive/refs/heads/main.zip -O ${GitHubRepo}-main.zip
          unzip ${GitHubRepo}-main.zip
          cd ${GitHubRepo}-main
          echo "Executing user data script from $USER_DATA_PATH" | tee -a /home/ec2-user/user-data.log
          source $USER_DATA_PATH | tee -a /home/ec2-user/user-data.log
          echo "User data script executed successfully" | tee -a /home/ec2-user/user-data.log

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt K3sInstance.PublicIp
  WebURL:
    Description: URL to access the web server
    Value: !Sub "http://${K3sInstance.PublicDnsName}/"