Description: S3 bucket for GitOps artifacts (k3s logs, kubeconfigs, etc.)

Parameters:
  TenantId:
    Type: String
    Default: Main
  
  EnvId:
    Type: String
    Default: Main

  BucketName:
    Type: String
    Default: ""
    Description: S3 bucket name for GitOps artifacts (must be globally unique and lowercase)

Conditions:
  HasName: !Equals [!Ref BucketName, ""]

Resources:
  GitopsArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If [HasName, !Ref BucketName, !Sub ${TenantId}-${EnvId}-artifacts-${AWS::AccountId}]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: TenantId
          Value: !Sub ${TenantId}
        - Key: EnvId
          Value: !Sub ${EnvId}
Outputs:
  ArtifactsBucketName:
    Description: Name of the S3 bucket for GitOps artifacts
    Value: !Ref GitopsArtifactsBucket
    Export:
      Name: !Sub ${TenantId}-${EnvId}-ArtifactsBucketName
